import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.73'
    id 'net.darkhax.curseforgegradle' version '1.1.24'
    id "com.modrinth.minotaur" version "2.+"
}

version = "${minecraft_version}-${mod_version}"
group = mod_group_id

repositories {
    mavenLocal()

    maven {
        name = "Curse Maven"
        url = uri("https://cursemaven.com")
        content {
            includeGroup("curse.maven")
        }
    }
}
base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)




neoForge {
    version = project.neo_version

    parchment {
        minecraftVersion = '1.21.1'
        mappingsVersion = '2024.11.17'
    }

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
        }

        client {
            client()
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
            programArgument '--nogui'
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        bblcore {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    //JEI

    compileOnly "curse.maven:jei-238222:6614392"
    runtimeOnly "curse.maven:jei-238222:6614392"

    //KubeJS
    compileOnly "curse.maven:kubejs-238086:5631423"
    runtimeOnly "curse.maven:kubejs-238086:5631423"

    //Rhino
    compileOnly "curse.maven:rhino-416294:5650008"
    runtimeOnly "curse.maven:rhino-416294:5650008"

    //BH Menu
    compileOnly "curse.maven:bisecthosting-server-integration-menu-neoforge-1084468:5762091"
    runtimeOnly "curse.maven:bisecthosting-server-integration-menu-neoforge-1084468:5762091"

    //Framed Blocks
    //compileOnly "curse.maven:framedblocks-441647:6872949"
    //runtimeOnly "curse.maven:framedblocks-441647:6872949"

    //Oritech
    compileOnly "curse.maven:oritech-1030830:6807350"
    runtimeOnly "curse.maven:oritech-1030830:6807350"

    //Architectury
    compileOnly "curse.maven:architectury-api-419699:5786327"
    runtimeOnly "curse.maven:architectury-api-419699:5786327"

    //Athena
    compileOnly "curse.maven:athena-841890:6669522"
    runtimeOnly "curse.maven:athena-841890:6669522"

    //owo-lib
    compileOnly "curse.maven:owo-lib-532610:6785734"
    runtimeOnly "curse.maven:owo-lib-532610:6785734"

    //geckolib
    compileOnly "curse.maven:geckolib-388172:6920810"
    runtimeOnly "curse.maven:geckolib-388172:6920810"

    //

    //Framed Block

    //Mekanism
    //compileOnly "curse.maven:mekanism-268560:5574951"
    //runtimeOnly "curse.maven:mekanism-268560:5574951"

    //EMI

    //compileOnly "curse.maven:emi-580555:5619579"
    //runtimeOnly "curse.maven:emi-580555:5619579"

}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {

        maven {
            url "https://cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }

        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

tasks.register('publishCurseForge', TaskPublishCurseForge) {
    group "modpublishing"

    apiToken = System.getenv("curseforge_token").toString()

    def projectId = 1135181
    def mainFile = upload(projectId, jar)

    mainFile.changelog = changelog
    mainFile.releaseType = "release"
    mainFile.gameVersions.addAll("1.21", "1.21.1")
    mainFile.addModLoader("neoforge")
    mainFile.addEnvironment("server", "client")

}


tasks.getByName("modrinth").setGroup("modpublishing")

modrinth {
    token = System.getenv("modrinth_token").toString()
    projectId = "tfpHINm8"
    versionType = "release"
    versionName = "bbl-core-" + "$minecraft_version" + "-" + "$mod_version"
    uploadFile = jar // With Loom, this MUST be set to `remapJar` instead of `jar`!

    gameVersions.addAll("1.21", "1.21.1")

    loaders = ["neoforge"]
    changelog = project.changelog
    dependencies {
        optional.project "jei"
    }
}

