# JVM and Gradle settings
org.gradle.jvmargs=-Xmx4608M
org.gradle.daemon=false
org.gradle.debug=false

# NeoForge conventions
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

## Environment Properties
minecraft_version=26.1
minecraft_version_range=[26.1.0.0-alpha,)
neo_version=26.1.0.0-alpha.15+pre-3
neo_version_range=[26.1.0.0-alpha,)
loader_version_range=[4,)

## Mod Properties
mod_id=bblcore
mod_name=BBL Core
mod_license=MIT
mod_version=12.1.9
mod_group_id=com.benbenlaw.core
mod_authors=benbenlaw
mod_description=Provide a lot of useful utilities and features for mods and modpacks

## JEI (optional, if used)
jei_mc_version=26.1-pre-3
jei_version=29.1.0.16